#spring-music.yaml
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nodeapi 
spec:
  selector:
    matchLabels:
      app: nodeapi 
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nodeapi 
    spec:
      containers:
      - name: nodeapi 
        image: taranggupta1987/api:latest # change to your docker account
        imagePullPolicy: Always
        env:
          - name: PORT
            value: "8080"
        ports:
        - containerPort: 8080
          protocol: TCP
